// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA41sXm-Zv9Mw3Vie1pVErn2njJoIhCuTs',
    appId: '1:1013089563611:web:1c2cbfca85f85b41b1edfe',
    messagingSenderId: '1013089563611',
    projectId: 'mon-projet-cours',
    authDomain: 'mon-projet-cours.firebaseapp.com',
    storageBucket: 'mon-projet-cours.firebasestorage.app',
    measurementId: 'G-H2CW73DZ8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1-73xbOLNHRTCpQy936pNeHYNFFnW_6c',
    appId: '1:1013089563611:android:a4e6adbde9778fdab1edfe',
    messagingSenderId: '1013089563611',
    projectId: 'mon-projet-cours',
    storageBucket: 'mon-projet-cours.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDInAc78YYRt7rfqTNeZn6j4sNpTkYEI4',
    appId: '1:1013089563611:ios:884021b121126a41b1edfe',
    messagingSenderId: '1013089563611',
    projectId: 'mon-projet-cours',
    storageBucket: 'mon-projet-cours.firebasestorage.app',
    iosBundleId: 'com.example.monProjetCours',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDInAc78YYRt7rfqTNeZn6j4sNpTkYEI4',
    appId: '1:1013089563611:ios:884021b121126a41b1edfe',
    messagingSenderId: '1013089563611',
    projectId: 'mon-projet-cours',
    storageBucket: 'mon-projet-cours.firebasestorage.app',
    iosBundleId: 'com.example.monProjetCours',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA41sXm-Zv9Mw3Vie1pVErn2njJoIhCuTs',
    appId: '1:1013089563611:web:9a683024b0cfc246b1edfe',
    messagingSenderId: '1013089563611',
    projectId: 'mon-projet-cours',
    authDomain: 'mon-projet-cours.firebaseapp.com',
    storageBucket: 'mon-projet-cours.firebasestorage.app',
    measurementId: 'G-9BSL3F7YYZ',
  );
}
